sudo: required

services:
  - docker
  
before_install:
  - docker build -t govkumardocker/docker-demo-app:latest .
  
script:
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
  - docker push govkumardocker/docker-demo-app